In [1]:
ls

food.db  quickbite.db  sample_data/

In [3]:
import sqlite3
import pandas as pd

In [4]:
conn = sqlite3.connect('food.db')

In [5]:
type(conn)

sqlite3.Connection

In [6]:
pd.read_sql_query("PRAGMA database_list", conn)

   seq  name              file
0    0  main  /content/food.db

In [7]:
conn.execute("ATTACH DATABASE 'quickbite.db' AS quickbite")

In [8]:
pd.read_sql_query("PRAGMA database_list", conn)

   seq       name                   file
0    0       main       /content/food.db
1    2  quickbite  /content/quickbite.db

In [12]:
# List the tables
pd.read_sql_query("SELECT name FROM main.sqlite_master WHERE type = 'table'", conn)

          name
0  restaurants
1       orders

In [13]:
pd.read_sql_query("SELECT name FROM quickbite.sqlite_master WHERE type = 'table'", conn)

       name
0  branches
1    orders

In [14]:
pd.read_sql_query("PRAGMA quickbite.table_info('branches')", conn)

   cid         name     type  notnull dflt_value  pk
0    0    branch_id  INTEGER        0       None   1
1    1  branch_name     TEXT        1       None   0
2    2         city     TEXT        1       None   0
3    3  opened_year  INTEGER        1       None   0

In [15]:
conn.close()

In [16]:
pd.read_sql_query("PRAGMA database_list", conn)

ProgrammingError: Cannot operate on a closed database.